# Pull the Node image from Docker Hub
FROM node:20

# Create a dedicated user for running the application
RUN adduser --disabled-login --gecos "" appuser

# Set the user for RUN, CMD or ENTRYPOINT calls from now on
USER appuser

# Configure the working directory
WORKDIR /home/appuser

# Copy the main application to working directory
COPY --chown=appuser . ./

# Install dependencies
RUN npm install

# Expose port 3000 to the Docker host
EXPOSE 3000

# Start the React app
CMD ["npm", "run", "dev"]