version: '3.8'

volumes:
  app-mongodata:
    driver: local

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.${ENV}
    ports:
      -  "3000:3000"
    container_name: visortest_frontend
    depends_on:
      - api
  api:
    build:
      context: ./api
      dockerfile: Dockerfile.${ENV}
    ports:
      -  "4369:4369"
    container_name: visortest_backend
    depends_on:
      - db
  db:
    volumes:
      - app-mongodata:/data
    image: mongo:5.0
    ports:
      - "5432:5432"