version: '3.8'

volumes:
  app-mongodata:
    driver: local

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.${ENV}
    environment:
      - PORT=${APP_PORT}
    ports:
      -  "${APP_PORT}:${APP_PORT}"
    container_name: visortest_frontend
    depends_on:
      - api
  api:
    build:
      context: ./api
      dockerfile: Dockerfile.${ENV}
    environment:
      - PORT=${API_PORT}
    ports:
      -  "${API_PORT}:${API_PORT}"
    container_name: visortest_backend
    depends_on:
      - db
  db:
    volumes:
      - app-mongodata:/data
    image: mongo:5.0
    container_name: visortest_db
    ports:
      - "${DB_PORT}:${DB_PORT}"
